name: hl Awake

on:
  workflow_dispatch:
  schedule:
    - cron: "1,11,22,33,44,55 * * * *"
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: mikeesto/heroku-awake@1.0.0
        with:
          URL: "http://houlang.site/discuz/?fromuid=167"
