name: hl Awake

on:
  workflow_dispatch:
  schedule:
    - cron: "0,10,20,30,40,50 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: mikeesto/heroku-awake@1.0.0
        with:
          URL: "http://houlang.site/discuz/?fromuid=167"
