name: hl Awake

on:
  schedule:
    - cron: "*/6 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: mikeesto/heroku-awake@1.0.0
        with:
          URL: "http://houlang.site/discuz/?fromuid=167"
